// sql 문 버전 관리 문서

// member table 생성
drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

// member table에 멤버 추가
insert into member(name) values('spring');
insert into member(name) values('spring2');